//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Comments = new HashSet<Comment>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int Id_Hotel { get; set; }

        [Display(Name = "Hotel name")]
        public string Name_Hotel { get; set; }
        [Display(Name = "Address")]
        public string Address_Hotel { get; set; }
        [Display(Name = "City hotel")]
        public string City_Hotel { get; set; }
        public int Stars { get; set; }
        [Display(Name = "Id user")]
        public Nullable<int> Id_user { get; set; }
        [Display(Name = "Description hotel")]
        public string Description_Hotel { get; set; }
        [Display(Name = "Image hotel")]
        public string Image_Hotel { get; set; }
        [Display(Name = "Number room")]
        public Nullable<int> Number_Room { get; set; }
        public string Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
