//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Hotels = new HashSet<Hotel>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id_user { get; set; }

        [Required(ErrorMessage ="This field is required")]
        [Display(Name = "First name")]
        public string First_Name { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Last name")]
        public string Last_Name { get; set; }

        //[Required(ErrorMessage = "This field is required")]
        //[Display(Name = "Password")]
        public string Email { get; set; }

        //[Required(ErrorMessage = "This field is required")]
        [Display(Name = "Password")]
        public string Pwd { get; set; }
        public Nullable<bool> Roles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
